### PR TITLE
Added "reducing JPEG quality", "Get length of image sides", "Get smallest side of image"

### PR DESCRIPTION
**Pull request by Demuzx**
Hello. Can you modify and update your code, with this implementations?

### CODE REVIEW

**Comment by disintegration** [comment]
Hello, 
I don't think these functions are useful enough to be included into the package.
* `GetSides` - just use `src.Bounds().Dx()` and `src.Bounds().Dy()`.
* `GetSmallestSide` - it's a simple `if` condition, no need to create a separate function.
* As for JPEG quality, `imaging.Save` is a helper function for simple use-cases. If you want extra options you should use format-specific encoders directly (e.g. jpeg.Encode, gif.Encode etc).

**Comment by Demuzx** [comment]
You have created a package to simplify the programming process. I spent 1 hour studying on the Internet how to use the encoder and reduce the quality of jpeg. Encoder options is the only missing your package for comfortable programming. In any case, your package always increases the size of original  image. This is not good. I think you need to give users the ability to simply control to change an image quality.

**Comment by disintegration** [comment]
You're right, the increased image sizes can be problematic...

I'm considering implementing a slightly different approach - functional options.
(See https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis).

For example:

```
// Save with the default quality.
err := imaging.Save(img, "test.jpg")

// Save with quality = 80.
err := imaging.Save(img, "test.jpg", imaging.JPEGQuality(80))
```

And the function signature will be

```
func Save(img image.Image, filename string, opts ...EncodeOption) (err error) 
```

This way there's a possibility to add more format-specific options in future.

What do you think?

**Comment by disintegration** [comment]
I just implemented it and added the example to docs:
https://godoc.org/github.com/disintegration/imaging#Save

**Pull request closed without merging**
