### PR TITLE
Added WebP support

### PR DESCRIPTION
**Pull request by abelkuruvilla**
Added WebP Support for Image Encoding

### CODE REVIEW

**Comment by disintegration** [comment]
Thank you for the contribution!

As of now `imaging` imports a few decoding/encoding packages to support opening and saving images using `Open` and `Save` helper functions: JPEG, PNG, GIF (using Go standard packages), TIFF, BMP (using golang.org/x/image/* subrepositories). I have no plans on adding more formats to the list.

- Adding a new format means adding a new dependency to `imaging`. I would like to keep external dependencies to the minimum. In addition, the `github.com/harukasan/go-libwebp` package uses CGO. This would make `imaging` harder to use for other people.
- It's usually trivial to add support for a new image format by using the decoding/encoding package directly. (E.g. use `webp.Encode(...)` instead of `imaging.Encode(...)`)

**Comment by demdxx** [comment]
@disintegration There is the support of WEBP in golang.org/x/image/webp
If you have no time I don't mind to add this package support for you

**Comment by abelkuruvilla** [comment]
@demdxx I had seen the package, but it only supports webp encoding. It does not support webp decoding

**Comment by demdxx** [comment]
Yes you are right

**Pull request closed without merging**
