### PR TITLE
Add resize benchmarks

### PR DESCRIPTION
**Pull request by ComSecNinja**
Add resize benchmarks based on 1000 resizes from 512x512 to 128x128

### CODE REVIEW

**Comment by ComSecNinja** [comment]
Just a thought... Should tests include benchmarking aswell? That way `text/template` could be used to generate a new `README.md`, maybe even going as far as getting notified on `go test` if performance goes up or down.

**Comment by disintegration** [comment]
I think the benchmark results will be quite different depending on the source and destination image sizes. If so, these numbers will be not very helpful. For example, can you run the same benchmark to resize an image from 1000x1000 to 100x100, then from 1000x1000 to 900x900, and then from 1000x1000 to 2000x2000. Also can you show your code so I can test it too?

As for generating readme.md using templates - I don't think it's really needed. 

Adding some benchmarks to the *_test.go files is definitely a good idea.

**Comment by ComSecNinja** [comment]
Sure. I'll rewrite my tests [here](https://github.com/ComSecNinja/imaging-benchmark). My intention with this package is also to provide you some kind of `benchmark.ResultSet` via `benchmark.Benchmark()` call for better integration if you deem it fit.

**Comment by ComSecNinja** [comment]
Allright, almost done here. Just missing the comparisons of averages to `NearestNeighbor`.

Right now running `go test` in [my package](https://github.com/ComSecNinja/imaging-benchmark) produces something like this:
data
Internal test uses a generated noise image. In your tests you could use the provided [generation functions](https://github.com/ComSecNinja/imaging-benchmark/blob/master/generators.go) or pass your own `image.Image` you get via e.g. `imaging.Open` to `benchmark.Benchmark(img image.Image, rounds int, ...benchmark.Size)`. See [internal test](https://github.com/ComSecNinja/imaging-benchmark/blob/master/benchmark_test.go) for example.

**Comment by ComSecNinja** [comment]
Now with comparisons. Very interesting numbers indeed!
data2

**Comment by disintegration** [comment]
Thank you!
Now we can see, that the speed comparison against nearest neighbour filter depends on the source and destination image sizes. It can be 46%, 25%, or 14 % for Catmull-Rom filter for example. So adding the some of the numbers in the table in readme would be not very informative.

**Comment by ComSecNinja** [comment]
You're absolutely right. Initially I just used the same resizing case as in that table, 512px² to 128px².

**Comment by disintegration** [comment]
Anyway, thank you for these benchmarks. The results was very interesting.

**Pull request closed without merging**
