### PR TITLE
Added CropTop function

### PR DESCRIPTION
**Pull request by brianhama**
This is a very useful helper function for many applications, such as when cropping user profile photos.

### CODE REVIEW

**Comment by disintegration** [comment]
I like the idea, but maybe it will be better to create a more generic function then? It could be named `CropAnchor` or `CropToSize` or something like this. For example:

```go
const (
    Center Anchor = iota
    TopLeft
    Top
    TopRight
    Left
    Right
    BottomLeft
    Bottom
    BottomRight
)

func CropAnchor(img image.Image, width, height int, anchor Anchor) *image.NRGBA {
    // ...
}
```
Not much more to type, but more utility:
```go
img = imaging.CropAnchor(img, 100, 100, imaging.Top)
```
What do you think?

**Comment by brianhama** [comment]
I like the idea of CropAnchor.  I've seen that same convention used before in image libraries for other languages.

**Comment by disintegration** [comment]
OK. I can add the Anchor version of the function when I have enough time. Maybe this weekend. Or you can update your pull request if you wish.

**Comment by disintegration** [comment]
CropAnchor function added, so I'm closing this pull request: https://github.com/disintegration/imaging/commit/a806ad60dee047a720f14c6c6b4e7ef43bc7d536

**Pull request closed without merging**
