### PR TITLE
Add Fill function

### PR DESCRIPTION
**Pull request by morphar**
Similar to a reverse Fit.

It scales the image to fill the specified width and height.
It uses an Anchor to determine how to crop any excessive pixels.

Tests not done as I haven't got a clue on how to do those.

### CODE REVIEW

**Comment by disintegration** [comment]
It's the same as the `Thumbnail` function, with the exception that it allows to specify an anchor mode for cropping. I think it will be useful. Thanks for the contribution!

**Comment by morphar** [comment]
You are very welcome! Thanks for merging!
And thanks for all your work on this great library - It has saved me many hours of work!

I just noticed I forgot to change the usage example though:
```
//		dstImage := imaging.Fill(srcImage, 800, 600, imaging.Lanczos)
```

Should have been:

```
//		dstImage := imaging.Fill(srcImage, 800, 600, imaging.TopLeft, imaging.Lanczos)
```

Do you want me to create another Pull request or is it easier for you to just fix with some other changes? :)

**Comment by disintegration** [comment]
No need. I've already fixed the usage example and added some tests just after merging.

**Comment by morphar** [comment]
Awesome! Thanks! :+1:

**Pull request merged**
